apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: ff-app
 name: ff-app
spec:
 replicas: 2
 selector:
   matchLabels:
     app: ff-app
 template:
   metadata:
     labels:
       app: ff-app
   spec:
     containers:
     - image: ritikharness/ff-app:latest
       name: ff-app
       ports:
       - containerPort: 30142
---
apiVersion: v1
kind: Service
metadata:
  name: ff-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 30142
  selector:
    app: ff-app

  
