# Deployment and Service Manifest for Harness CV App Example
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
   app: ff-app
 name: ff-app
spec:
  selector:
    matchLabels:
      app: ff-app
  replicas: 2 
  template:
    metadata:
      labels:
        app: ff-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
        - name: ff-app
          image: {{.Values.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1 
kind: Service 
metadata: 
  name: ff-app
spec:
  selector:
    app: ff-app
  ports:
    - protocol: "TCP"
      port: 8082 
      targetPort: 8082 
  type: LoadBalancer 




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#  labels:
#    app: ff-app
#  name: ff-app
# spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: ff-app
#  template:
#    metadata:
#      labels:
#        app: ff-app
#    spec:
#      containers:
#      - image: ritikharness/ff-app:latest
#        name: ff-app
#        ports:
#        - containerPort: 3007


